### ISSUE TITLE
Request to include atom syntax package for uxntal

### ISSUE THREAD

**Issue by autumnull** [hundredrabbits/awesome-uxn#11]
Hi, I just made [this atom package](https://atom.io/packages/language-uxntal) for syntax/language support in uxntal code - I was wondering if you could add it to your language support list. Best wishes!

**Comment by neauoire** [comment]
Sure :) Wanna open a PR?

**Comment by autumnull** [comment]
PR here: #12

**Comment by neauoire** [comment]
cheers :)
