### ISSUE TITLE
Addition of uxngb

### ISSUE THREAD

**Issue by tbsp** [hundredrabbits/awesome-uxn#14]
I'd like to shamelessly request that uxngb be added to the emulator list, despite being quite incomplete: https://github.com/tbsp/uxngb

**Comment by neauoire** [comment]
Wow, this is wondderful! Adding it right away <3

This fall, I will have access to my old gbc and I will definitely take this for a spin!

**Comment by tbsp** [comment]
Thanks! I've already managed to speed up the main instruction loop ~25% and unrolling MUL/DIV instructions has sped them up ~40% or so. Low-hanging optimizations for sure, but still nice to find.
