### ISSUE TITLE
uxn5 test suite

### ISSUE THREAD

**Issue by max22-** [hundredrabbits/awesome-uxn#16]
Maybe it could be nice to add a link to uxn5 test suite ?
[https://git.sr.ht/~rabbits/uxn5/tree/main/item/etc/tests.tal](https://git.sr.ht/~rabbits/uxn5/tree/main/item/etc/tests.tal)

**Comment by neauoire** [comment]
Good idea, I think the copy in the uxn repo is more up to date tho.
Wanna make a PR?

**Comment by max22-** [comment]
done !
