### ISSUE TITLE
My own uxn implementation (currently not named)

### ISSUE THREAD

**Issue by zzo38** [hundredrabbits/awesome-uxn#21]
I made up my own implementation of Uxn, which is public domain, and currently does not have a name. It is stored in a Fossil repository, which can be found at: http://zzo38computer.org/fossil/uxn.ui

Some features are currently incomplete or not implemented, such as audio (which might be implemented in future).

However, there are some additional features, such as possibility to adjust speed, pause, override date/time, restrict file system access, etc.

**Comment by neauoire** [comment]
You should open a PR, I've started to look at the code, and it's the first SDL1 implementation that I know of, once you've picked a name, submit a PR and I'll happily merge it :)

**Comment by zzo38** [comment]
Someone suggested names "zzouxn" or "uxn38". These names might work, unless you have a better suggestion?

**Comment by neauoire** [comment]
uxn38 is very good, I'd go with that.
