### ISSUE TITLE
potato

### ISSUE THREAD

**Issue by farvardin** [hundredrabbits/awesome-uxn#24]
why isn't Potato listed in the OS section?

https://git.sr.ht/~rabbits/potato

**Comment by neauoire** [comment]
Because it's still very much a work in progress

**Comment by farvardin** [comment]
how that, a work in progress?! It has already replaced Windows 10 on my main computer!

**Comment by neauoire** [comment]
Haha, that's both very cool and very sad. I've added it up the list then, thanks :)
